/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import calculadoraresistencias.CalculadoraResistencias;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.net.*;

import java.text.*;
import javax.swing.*;

/**
 *
 * @author rjbr
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/res.png"));


        return retValue;
    }
    // inicializacion de variables
    public int a, aa, aaa, t, tt, c = 0;
    public float k, kk = 0;

    //****
//metodo para resear variables
    public void resetA() {
        a = 0;

    }

    public void resetAA() {

        aa = 0;
    }

    public void resetAAA() {
        aaa = 0;
    }

    public void resetK() {
        k = 0;
    }

    public void resetT() {
        t = 0;
    }

    public void resetKK() {
        kk = 0;
    }

    public void resetC() {

        c = 0;
    }

//termina metodo
    //METODO PARA CONCATENAR
    DecimalFormat f = new DecimalFormat("###,###.##");

    public void operacion(int a, int aa, float k) {
        //CONCATENA LAS DOS PRIMERAS BANDAS
        String conc = a + "" + aa;
        int var = Integer.valueOf(conc);
// MULTIPLICA LAS DOS BANDAS POR LA TERCERA
        int var2 = (int) (k * var);

        float var3 = var * k;

        //comparamos si la opcion elegida no es la primera en los combo box segun el indice
        if (combo41.getSelectedIndex() != 0 && combo42.getSelectedIndex() != 0 && combo43.getSelectedIndex() != 0) {

            lblResultado.setText("" + f.format(var3) + " ohms");
        } else {
            lblResultado.setText("");
        }
    }

    public void operacion2(int a, int aa, int aaa, float kk) {
        //CONCATENA LAS DOS PRIMERAS BANDAS
        String conc = a + "" + aa + "" + aaa;
        int var = Integer.valueOf(conc);
// MULTIPLICA LAS DOS BANDAS POR el multiplicador
        int var2 = (int) (kk * var);

        float var3 = var * kk;

        //comparamos si la opcion elegida no es la primera en los combo box segun el indice
        if (combo51.getSelectedIndex() != 0 && combo52.getSelectedIndex() != 0 && combo53.getSelectedIndex() != 0 && combo54.getSelectedIndex() != 0) {// si valor de multiplicar no es null realiza la multiplicacion

            lblVal2.setText("" + f.format(var3) + " ohms");
            //    lblVal3.setText("" + f.format(var3) + " ohms");
        } else {
            lblVal2.setText("");
        }
    }

    public void operacion3(int a, int aa, int aaa, float kk) {
        //CONCATENA LAS tres PRIMERAS BANDAS
        String conc = a + "" + aa + "" + aaa;
        int var = Integer.valueOf(conc);
// MULTIPLICA LAS tres BANDAS POR el multiplicador K
        int var2 = (int) (kk * var);

        float var3 = var * kk;

        //comparamos si la opcion elegida no es la primera en los combo box segun el indice
        if (combo61.getSelectedIndex() != 0 && combo62.getSelectedIndex() != 0 && combo63.getSelectedIndex() != 0 && combo64.getSelectedIndex() != 0) {// si valor de multiplicar no es null realiza la multiplicacion

            //       lblVal2.setText("" + f.format(var3) + " ohms");
            lblVal3.setText("" + f.format(var3) + " ohms");
        } else {
            lblVal3.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        combo41 = new javax.swing.JComboBox<>();
        combo42 = new javax.swing.JComboBox<>();
        lblBanda1 = new javax.swing.JLabel();
        combo44 = new javax.swing.JComboBox<>();
        lblT = new javax.swing.JLabel();
        combo43 = new javax.swing.JComboBox<>();
        lblBanda2 = new javax.swing.JLabel();
        lblBanda3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        combo51 = new javax.swing.JComboBox<>();
        combo52 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblVal2 = new javax.swing.JLabel();
        lblBanda22 = new javax.swing.JLabel();
        lblBanda25 = new javax.swing.JLabel();
        lblBanda23 = new javax.swing.JLabel();
        lblBanda21 = new javax.swing.JLabel();
        combo53 = new javax.swing.JComboBox<>();
        combo55 = new javax.swing.JComboBox<>();
        lblTol2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo54 = new javax.swing.JComboBox<>();
        lblBanda24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        combo61 = new javax.swing.JComboBox<>();
        combo62 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblVal3 = new javax.swing.JLabel();
        lblBanda62 = new javax.swing.JLabel();
        lblBanda65 = new javax.swing.JLabel();
        lblBanda63 = new javax.swing.JLabel();
        lblBanda61 = new javax.swing.JLabel();
        combo63 = new javax.swing.JComboBox<>();
        combo66 = new javax.swing.JComboBox<>();
        lblTol3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo64 = new javax.swing.JComboBox<>();
        lblBanda64 = new javax.swing.JLabel();
        combo65 = new javax.swing.JComboBox<>();
        lblBanda66 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Resistencias Ohms");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jTabbedPane1.setName("4 bandas"); // NOI18N

        jPanel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        combo41.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo41.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 1", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo41MouseClicked(evt);
            }
        });
        combo41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo41ActionPerformed(evt);
            }
        });

        combo42.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo42.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 2", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo42ActionPerformed(evt);
            }
        });

        combo44.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo44.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tolerancia", "Oro", "Plata", "Sin color" }));
        combo44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo44ActionPerformed(evt);
            }
        });

        combo43.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo43.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 3", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Oro", "Plata" }));
        combo43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo43ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Valor resistencia:");

        lblResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Tolerancia de:");

        lblRes2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo41, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBanda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblT, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(combo42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(combo44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addGap(107, 107, 107))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblT, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );

        jTabbedPane1.addTab("<html>\n\t<font face=\"Ubuntu\" size=\"4\">\n    \t    \t<b>\n    \t\t\t  4 Bandas\n \t\t </b>\n\t</font>\n</html>\n\n", jPanel2);

        jPanel3.setLayout(null);

        combo51.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo51.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 1", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo51MouseClicked(evt);
            }
        });
        combo51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo51ActionPerformed(evt);
            }
        });
        jPanel3.add(combo51);
        combo51.setBounds(10, 31, 81, 23);

        combo52.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo52.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 2", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo52ActionPerformed(evt);
            }
        });
        jPanel3.add(combo52);
        combo52.setBounds(101, 31, 77, 23);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Valor resistencia:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(46, 81, 150, 30);

        lblVal2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jPanel3.add(lblVal2);
        lblVal2.setBounds(206, 81, 112, 30);
        jPanel3.add(lblBanda22);
        lblBanda22.setBounds(101, 60, 77, 15);
        jPanel3.add(lblBanda25);
        lblBanda25.setBounds(362, 60, 92, 14);
        jPanel3.add(lblBanda23);
        lblBanda23.setBounds(188, 60, 81, 15);
        jPanel3.add(lblBanda21);
        lblBanda21.setBounds(10, 60, 81, 15);

        combo53.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo53.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 3", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo53ActionPerformed(evt);
            }
        });
        jPanel3.add(combo53);
        combo53.setBounds(188, 31, 81, 23);

        combo55.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo55.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tolerancia", "Marrón", "Rojo", "Oro", "Plata" }));
        combo55.setNextFocusableComponent(combo54);
        combo55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo55ActionPerformed(evt);
            }
        });
        jPanel3.add(combo55);
        combo55.setBounds(362, 31, 92, 23);

        lblTol2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jPanel3.add(lblTol2);
        lblTol2.setBounds(206, 122, 98, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Tolerancia de:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(75, 122, 121, 30);

        combo54.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo54.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 4", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Oro", "Plata" }));
        combo54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo54ActionPerformed(evt);
            }
        });
        jPanel3.add(combo54);
        combo54.setBounds(275, 31, 81, 23);
        jPanel3.add(lblBanda24);
        lblBanda24.setBounds(275, 60, 81, 15);

        jTabbedPane1.addTab("<html>\n\t<font face=\"Ubuntu\" size=\"4\">\n    \t    \t<b>\n    \t\t\t  5 Bandas\n \t\t </b>\n\t</font>\n</html>\n\n", jPanel3);

        combo61.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo61.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 1", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo61MouseClicked(evt);
            }
        });
        combo61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo61ActionPerformed(evt);
            }
        });

        combo62.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo62.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 2", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo62ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Valor resistencia:");

        lblVal3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        combo63.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo63.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 3", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado", "Gris", "Blanco" }));
        combo63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo63ActionPerformed(evt);
            }
        });

        combo66.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo66.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coeficiente ", "Marrón", "Rojo", "Amarillo", "Naranja", "Azul", "Morado", "Blanco" }));
        combo66.setNextFocusableComponent(combo54);
        combo66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo66ActionPerformed(evt);
            }
        });

        lblTol3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Tolerancia de:");

        combo64.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo64.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda 4", "Negro", "Marrón", "Rojo", "Naranja", "Amarillo", "Oro", "Plata" }));
        combo64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo64ActionPerformed(evt);
            }
        });

        combo65.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        combo65.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tolerancia", "Marrón", "Rojo", "Oro", "Plata" }));
        combo65.setNextFocusableComponent(combo54);
        combo65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo65ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBanda61, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblBanda62, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblBanda63, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblBanda64, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblBanda65, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBanda66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(combo61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(combo62, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(combo63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(combo64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(combo65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVal3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTol3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBanda61, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda62, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda63, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda64, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda65, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda66, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVal3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTol3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("<html>\n\t     Coeficiente de \t <br>\n\t temperatura      :\n</html>");

        lblTemp.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(lblTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("<html>\n\t<font face=\"Ubuntu\" size=\"4\">\n    \t    \t<b>\n    \t\t\t  6 Bandas\n \t\t </b>\n\t</font>\n</html>\n\n", jPanel4);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email-2-icon_1.png"))); // NOI18N
        jLabel9.setToolTipText("Contacto");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-icon.png"))); // NOI18N
        jLabel10.setToolTipText("Cerrar aplicación");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        jLabel8.setToolTipText("Guía de colores");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo41ActionPerformed
// COMBO BOX BANDA 1---------------------------------------------------------
        switch (combo41.getSelectedIndex()) {
            case 0:
                resetA(); //resetea la variable si se hacen varias selecciones 
                lblBanda1.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda1.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                a = 0;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.BLACK);
                break;

            case 2:
                a = 1;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                a = 2;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.red);
                break;

            case 4:
                a = 3;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.orange);
                break;

            case 5:
                a = 4;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.yellow);
                break;

            case 6:
                a = 5;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.green);
                break;
            case 7:
                a = 6;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.blue);
                break;
            case 8:
                a = 7;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.MAGENTA);
                break;
            case 9:
                a = 8;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.GRAY);
                break;
            case 10:
                a = 9;
                lblBanda1.setOpaque(true);
                lblBanda1.setBackground(Color.white);
                break;

        }
        System.out.println("a -" + a);
        System.out.println("aa -" + aa);
        System.out.println("k- " + k);
        operacion(a, aa, k);

    }//GEN-LAST:event_combo41ActionPerformed

    private void combo42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo42ActionPerformed
        //COMBO BOX BANDA 2 -------------------------------------

        switch (combo42.getSelectedIndex()) {
            case 0:
                resetAA(); //resetea la variable si se hacen varias selecciones 
                lblBanda2.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda2.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                aa = 0;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.BLACK);
                break;

            case 2:
                aa = 1;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                aa = 2;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.red);
                break;

            case 4:
                aa = 3;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.orange);
                break;

            case 5:
                aa = 4;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.yellow);
                break;

            case 6:
                aa = 5;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.green);
                break;
            case 7:
                aa = 6;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.blue);
                break;
            case 8:
                aa = 7;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.MAGENTA);
                break;
            case 9:
                aa = 8;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.GRAY);
                break;
            case 10:
                aa = 9;
                lblBanda2.setOpaque(true);
                lblBanda2.setBackground(Color.white);
                break;
    }//GEN-LAST:event_combo42ActionPerformed
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("k- " + k);
        operacion(a, aa, k);
    }

    private void combo44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo44ActionPerformed
        // COMBO BANDA 4 O TOLERANCIA --------------------------------------------

        switch (combo44.getSelectedIndex()) {
            case 0:
                resetT();
                lblT.setOpaque(true);
                lblT.setBackground(new Color(240, 240, 240));
                break;

            case 1:
                t = 5;
                lblT.setOpaque(true);
                lblT.setBackground(new Color(255, 215, 0));
                break;

            case 2:
                t = 10;
                lblT.setOpaque(true);
                lblT.setBackground(new Color(230, 230, 250));
                break;

            case 3:
                t = 20;
                lblT.setOpaque(true);
                lblT.setBackground(new Color(240, 240, 240));
                break;

            case 4:
                break;

            case 5:
                break;

            case 6:
                break;

            case 7:
                break;

            case 8:
                break;
            case 9:
                break;
        }
        if (combo44.getSelectedIndex() != 0) {
            lblRes2.setText("+/- " + t + " %");
        } else {
            lblRes2.setText("");
        }
    }//GEN-LAST:event_combo44ActionPerformed

    private void combo43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo43ActionPerformed
        // COMBO BANDA 3 -------------------------------------------------
        switch (combo43.getSelectedIndex()) {
            case 0:
                resetK(); //resetea la variable si se hacen varias selecciones 
                lblBanda3.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda3.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                k = 1;
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.BLACK);
                break;

            case 2:
                k = (int) Math.pow(10, 1);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                k = (int) Math.pow(10, 2);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.red);
                break;

            case 4:
                k = (int) Math.pow(10, 3);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.orange);
                break;

            case 5:
                k = (int) Math.pow(10, 4);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.yellow);
                break;

            case 6:
                k = (int) Math.pow(10, 5);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.green);
                break;
            case 7:
                k = (int) Math.pow(10, 6);
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(Color.blue);
                break;
//            case 8:
//                k = (int) Math.pow(10, 7);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.MAGENTA);
//                break;
//            case 9:
//                k = (int) Math.pow(10, 8);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.GRAY);
//                break;
//            case 10:
//                k = (int) Math.pow(10, 9);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.white);
//                break;
            case 11:
                k = (float) 0.1;
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(new Color(255, 215, 0));// color oro
                break;
            case 12:
                k = (float) 0.01;
                lblBanda3.setOpaque(true);
                lblBanda3.setBackground(new Color(230, 230, 250));//color plataS
        }

        operacion(a, aa, k);
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("k- " + k);
    }//GEN-LAST:event_combo43ActionPerformed

    private void combo41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo41MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_combo41MouseClicked

    private void combo51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo51MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combo51MouseClicked

    private void combo51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo51ActionPerformed
        // COMBO 51 PRIMERA BANDA de 5 bandas----------------------

        switch (combo51.getSelectedIndex()) {
            case 0:
                resetA(); //resetea la variable si se hacen varias selecciones 
                lblBanda21.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda21.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                a = 0;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.BLACK);
                break;

            case 2:
                a = 1;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                a = 2;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.red);
                break;

            case 4:
                a = 3;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.orange);
                break;

            case 5:
                a = 4;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.yellow);
                break;

            case 6:
                a = 5;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.green);
                break;
            case 7:
                a = 6;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.blue);
                break;
            case 8:
                a = 7;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.MAGENTA);
                break;
            case 9:
                a = 8;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.GRAY);
                break;
            case 10:
                a = 9;
                lblBanda21.setOpaque(true);
                lblBanda21.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion2(a, aa, aaa, kk);

    }//GEN-LAST:event_combo51ActionPerformed

    private void combo52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo52ActionPerformed
        // COMBO 52 SEGUNDA BANDA de 5 bandas---------------------
        switch (combo52.getSelectedIndex()) {
            case 0:
                resetAA(); //resetea la variable si se hacen varias selecciones 
                lblBanda22.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda22.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                aa = 0;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.BLACK);
                break;

            case 2:
                aa = 1;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                aa = 2;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.red);
                break;

            case 4:
                aa = 3;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.orange);
                break;

            case 5:
                aa = 4;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.yellow);
                break;

            case 6:
                aa = 5;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.green);
                break;
            case 7:
                aa = 6;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.blue);
                break;
            case 8:
                aa = 7;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.MAGENTA);
                break;
            case 9:
                aa = 8;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.GRAY);
                break;
            case 10:
                aa = 9;
                lblBanda22.setOpaque(true);
                lblBanda22.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion2(a, aa, aaa, kk);


    }//GEN-LAST:event_combo52ActionPerformed

    private void combo53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo53ActionPerformed
        // combo 53 tercera banda de 5 bandas

        switch (combo53.getSelectedIndex()) {
            case 0:
                resetAAA(); //resetea la variable si se hacen varias selecciones 
                lblBanda23.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda23.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                aaa = 0;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.BLACK);
                break;

            case 2:
                aaa = 1;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(new Color(156, 93, 82));//marron
                break;

            case 3:
                aaa = 2;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.red);
                break;

            case 4:
                aaa = 3;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.orange);
                break;

            case 5:
                aaa = 4;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.yellow);
                break;

            case 6:
                aaa = 5;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.green);
                break;
            case 7:
                aaa = 6;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.blue);
                break;
            case 8:
                aaa = 7;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.MAGENTA);
                break;
            case 9:
                aaa = 8;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.GRAY);
                break;
            case 10:
                aaa = 9;
                lblBanda23.setOpaque(true);
                lblBanda23.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion2(a, aa, aa, kk);


    }//GEN-LAST:event_combo53ActionPerformed

    private void combo55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo55ActionPerformed
        // COMBOBOX TOLERANCIA 5 BANDAS 55

        switch (combo55.getSelectedIndex()) {
            case 0:
                resetT();
                lblBanda25.setOpaque(true);
                lblBanda25.setBackground(new Color(240, 240, 240));
                break;

            case 1:
                t = 1;
                lblBanda25.setOpaque(true);
                lblBanda25.setBackground(new Color(156, 93, 82));//marron
                break;

            case 2:
                t = 2;
                lblBanda25.setOpaque(true);
                lblBanda25.setBackground(Color.red);
                break;

            case 3:
                t = 5;
                lblBanda25.setOpaque(true);
                lblBanda25.setBackground(new Color(255, 215, 0));// color oro
                break;

            case 4:
                t = 10;
                lblBanda25.setOpaque(true);
                lblBanda25.setBackground(new Color(230, 230, 250));//color plataS
                break;

            case 5:
                break;

            case 6:
                break;

            case 7:
                break;

            case 8:
                break;
            case 9:
                break;
        }

        if (combo55.getSelectedIndex() != 0) {
            lblTol2.setText("+/- " + t + " %");
        } else {
            lblTol2.setText("");
        }
    }//GEN-LAST:event_combo55ActionPerformed

    private void combo54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo54ActionPerformed
        // BANDA 54  5 bandas

        switch (combo54.getSelectedIndex()) {
            case 0:

                resetKK(); //resetea la variable si se hacen varias selecciones 
                lblBanda24.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda24.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                kk = 1;
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(Color.BLACK);
                break;

            case 2:
                kk = (int) Math.pow(10, 1);
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                kk = (int) Math.pow(10, 2);
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(Color.red);
                break;

            case 4:
                kk = (float) Math.pow(10, 3);
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(Color.orange);
                break;

            case 5:
                kk = (int) Math.pow(10, 4);
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(Color.yellow);
                break;
//
//            case 6:
//                k = (int) Math.pow(10, 5);
//                lblBanda24.setOpaque(true);
//                lblBanda3.setBackground(Color.green);
//                break;
//            case 7:
//                k = (int) Math.pow(10, 6);
//                lblBanda24.setOpaque(true);
//                lblBanda24.setBackground(Color.blue);
//                break;
//            case 8:
//                k = (int) Math.pow(10, 7);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.MAGENTA);
//                break;
//            case 9:
//                k = (int) Math.pow(10, 8);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.GRAY);
//                break;
//            case 10:
//                k = (int) Math.pow(10, 9);
//                lblBanda3.setOpaque(true);
//                lblBanda3.setBackground(Color.white);
//                break;
            case 6:
                kk = (float) 0.1;
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(new Color(255, 215, 0));// color oro
                break;
            case 7:
                kk = (float) 0.01;
                lblBanda24.setOpaque(true);
                lblBanda24.setBackground(new Color(230, 230, 250));//color plataS
        }

        operacion2(a, aa, aaa, kk);
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aa- " + aaa);
        System.out.println("k- " + kk);


    }//GEN-LAST:event_combo54ActionPerformed

    private void combo61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo61MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combo61MouseClicked

    private void combo61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo61ActionPerformed
        // COMBO 61 PRIMERA BANDA  6 RAYAS

        switch (combo61.getSelectedIndex()) {
            case 0:
                resetA(); //resetea la variable si se hacen varias selecciones 
                lblBanda61.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda61.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                a = 0;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.BLACK);
                break;

            case 2:
                a = 1;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                a = 2;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.red);
                break;

            case 4:
                a = 3;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.orange);
                break;

            case 5:
                a = 4;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.yellow);
                break;

            case 6:
                a = 5;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.green);
                break;
            case 7:
                a = 6;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.blue);
                break;
            case 8:
                a = 7;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.MAGENTA);
                break;
            case 9:
                a = 8;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.GRAY);
                break;
            case 10:
                a = 9;
                lblBanda61.setOpaque(true);
                lblBanda61.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion3(a, aa, aaa, kk);


    }//GEN-LAST:event_combo61ActionPerformed

    private void combo62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo62ActionPerformed
        // COMBO 62 BANDA 2 6 RAYAS

        switch (combo62.getSelectedIndex()) {
            case 0:
                resetAA(); //resetea la variable si se hacen varias selecciones 
                lblBanda62.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda62.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                aa = 0;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.BLACK);
                break;

            case 2:
                aa = 1;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                aa = 2;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.red);
                break;

            case 4:
                aa = 3;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.orange);
                break;

            case 5:
                aa = 4;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.yellow);
                break;

            case 6:
                aa = 5;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.green);
                break;
            case 7:
                aa = 6;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.blue);
                break;
            case 8:
                aa = 7;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.MAGENTA);
                break;
            case 9:
                aa = 8;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.GRAY);
                break;
            case 10:
                aa = 9;
                lblBanda62.setOpaque(true);
                lblBanda62.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion3(a, aa, aaa, kk);


    }//GEN-LAST:event_combo62ActionPerformed

    private void combo63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo63ActionPerformed
        //combo 63 raya 3

        switch (combo63.getSelectedIndex()) {
            case 0:
                resetAAA(); //resetea la variable si se hacen varias selecciones 
                lblBanda63.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda63.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                aaa = 0;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.BLACK);
                break;

            case 2:
                aaa = 1;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                aaa = 2;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.red);
                break;

            case 4:
                aaa = 3;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.orange);
                break;

            case 5:
                aaa = 4;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.yellow);
                break;

            case 6:
                aaa = 5;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.green);
                break;
            case 7:
                aaa = 6;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.blue);
                break;
            case 8:
                aaa = 7;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.MAGENTA);
                break;
            case 9:
                aaa = 8;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.GRAY);
                break;
            case 10:
                aaa = 9;
                lblBanda63.setOpaque(true);
                lblBanda63.setBackground(Color.white);
                break;

        }
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion3(a, aa, aaa, kk);


    }//GEN-LAST:event_combo63ActionPerformed

    private void combo66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo66ActionPerformed

//combo 66 coeficiente de calentamiento
        switch (combo66.getSelectedIndex()) {
            case 0:
                resetC();
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(new Color(240, 240, 240));
                break;

            case 1:
                c = 100;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(new Color(156, 93, 82));//marron
                break;

            case 2:
                c = 50;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.red);
                break;

            case 3:
                c = 25;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.yellow);
                break;

            case 4:
                c = 15;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.orange);
                break;
            case 5:
                c = 10;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.blue);

                break;
            case 6:
                c = 5;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.magenta);
                break;
            case 7:
                c = 1;
                lblBanda66.setOpaque(true);
                lblBanda66.setBackground(Color.white);

        }

        if (combo66.getSelectedIndex() != 0) {
            lblTemp.setText("" + c + " PPM/°C ");
        } else {
            lblTemp.setText("");
        }

    }//GEN-LAST:event_combo66ActionPerformed

    private void combo64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo64ActionPerformed
        // COMBO 64 MULTIPLICADOR K

        switch (combo64.getSelectedIndex()) {
            case 0:
                resetKK(); //resetea la variable si se hacen varias selecciones 
                lblBanda64.setOpaque(true); // hace posible aplicar color sobre label
                lblBanda64.setBackground(new Color(240, 240, 240)); // color gris que resetea las selecciones
                break;

            case 1:
                kk = 1;
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(Color.BLACK);
                break;

            case 2:
                kk = (int) Math.pow(10, 1);
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(new Color(156, 93, 82));
                break;

            case 3:
                kk = (int) Math.pow(10, 2);
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(Color.red);
                break;

            case 4:
               kk = (int) Math.pow(10, 3);
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(Color.orange);
                break;

            case 5:
                kk = (int) Math.pow(10, 4);
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(Color.yellow);
                break;

           
        
              case 6:
                kk = (float) 0.1;
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(new Color(255, 215, 0));// color oro
                break;
            case 7:
                kk = (float) 0.01;
                lblBanda64.setOpaque(true);
                lblBanda64.setBackground(new Color(230, 230, 250));//color plataS
        }
        
        
        
        
        System.out.println("a- " + a);
        System.out.println("aa- " + aa);
        System.out.println("aaa- " + aaa);
        System.out.println("k- " + kk);
        operacion3(a, aa, aaa, kk);


    }//GEN-LAST:event_combo64ActionPerformed

    private void combo65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo65ActionPerformed
        // combo tolerancia 65 6 rayas

        switch (combo65.getSelectedIndex()) {
            case 0:
                resetT();
                lblBanda65.setOpaque(true);
                lblBanda65.setBackground(new Color(240, 240, 240));
                break;

            case 1:
                t = 1;
                lblBanda65.setOpaque(true);
                lblBanda65.setBackground(new Color(156, 93, 82));//marron
                break;

            case 2:
                t = 2;
                lblBanda65.setOpaque(true);
                lblBanda65.setBackground(Color.red);
                break;

            case 3:
                t = 5;
                lblBanda65.setOpaque(true);
                lblBanda65.setBackground(new Color(255, 215, 0));// color oro
                break;

            case 4:
                t = 10;
                lblBanda65.setOpaque(true);
                lblBanda65.setBackground(new Color(230, 230, 250));//color plataS
                break;

        }

        if (combo65.getSelectedIndex() != 0) {
            lblTol3.setText("+/- " + t + " %");
        } else {
            lblTol3.setText("");
        }

    }//GEN-LAST:event_combo65ActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
//IMAGEN DE GUIA D ERESISTENCIAS gg
        String file = "codigo_colores.gif";
        File path = new File(file);
//try {
//          //  Desktop.getDesktop().open(new File("codigo_colores.gif"));
//            Desktop.getDesktop().open(path);
//        } catch (IOException e) {
//            e.printStackTrace();
//
//        }catch(IllegalArgumentException e){
//        JOptionPane.showMessageDialog(null, "No se encontró el archivo");
//        e.printStackTrace();
//        }
     
        try {
            //  Desktop.getDesktop().open(new File("codigo_colores.gif"));
//          ImageIcon imagen = new ImageIcon(getClass().getResource("/images/codigo_colores.gif")); 

            Desktop.getDesktop().open(path);
        } catch (IOException e) {
          //  e.printStackTrace();
            System.out.println(""+e);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "No se encontró el archivo");
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // IMAGEN CORREO
        
        JOptionPane.showMessageDialog(null,"Software de ayuda para el calculo del valor de  \n"
                + "resistencias según su numero de bandas. \n"
                + "\nCorreo de contacto:\n rjbr39@gmail.com" );
        
        
        
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // IMAGEN CERRAR APLICAION
        
        System.exit(0);



    }//GEN-LAST:event_jLabel10MousePressed

//
//jLabel8.addMouseListener(new MouseAdapter()  
//{  
//    @Override
//    public void mouseClicked(MouseEvent e)  
//    {  
//       // you can open a new frame here as
//       // i have assumed you have declared "frame" as instance variable
//       
//
//    }  
//
//            @Override
//            public void mousePressed(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//
//            @Override
//            public void mouseReleased(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//
//            @Override
//            public void mouseEntered(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//
//            @Override
//            public void mouseExited(MouseEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
//        }); 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo41;
    private javax.swing.JComboBox<String> combo42;
    private javax.swing.JComboBox<String> combo43;
    private javax.swing.JComboBox<String> combo44;
    private javax.swing.JComboBox<String> combo51;
    private javax.swing.JComboBox<String> combo52;
    private javax.swing.JComboBox<String> combo53;
    private javax.swing.JComboBox<String> combo54;
    private javax.swing.JComboBox<String> combo55;
    private javax.swing.JComboBox<String> combo61;
    private javax.swing.JComboBox<String> combo62;
    private javax.swing.JComboBox<String> combo63;
    private javax.swing.JComboBox<String> combo64;
    private javax.swing.JComboBox<String> combo65;
    private javax.swing.JComboBox<String> combo66;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBanda1;
    private javax.swing.JLabel lblBanda2;
    private javax.swing.JLabel lblBanda21;
    private javax.swing.JLabel lblBanda22;
    private javax.swing.JLabel lblBanda23;
    private javax.swing.JLabel lblBanda24;
    private javax.swing.JLabel lblBanda25;
    private javax.swing.JLabel lblBanda3;
    private javax.swing.JLabel lblBanda61;
    private javax.swing.JLabel lblBanda62;
    private javax.swing.JLabel lblBanda63;
    private javax.swing.JLabel lblBanda64;
    private javax.swing.JLabel lblBanda65;
    private javax.swing.JLabel lblBanda66;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTol2;
    private javax.swing.JLabel lblTol3;
    private javax.swing.JLabel lblVal2;
    private javax.swing.JLabel lblVal3;
    // End of variables declaration//GEN-END:variables
}
